#' Update variable labels of a `labelled` tibble
#'
#' Updates the variable labels of a tibble using
#' [labelled::set_variable_labels()]. The variables to be update should all have
#' a row in `new_var_labels`. Variables that don't won't be changed and will
#' keep their existing label.
#'
#' @param dat Tibble containing variables to be updated
#' @param new_var_labels Tibble with two columns, variable and label. i.e. the
#'   format generated by [tveDataLoader::get_varLabels()]. Column names don't
#'   matter, but the first column will be used as variable and the second as
#'   label, so they must be in that order.
#'
#' @examples
#' dat <- tibble(a = 1, b = 2)
#' tveDataLoader::get_varLabels(dat)
#' new_var_labs <- tibble::tribble(
#'   ~variable, ~label,
#'   "a", "variable 1",
#'   "b", "variable 2"
#' )
#' dat <- update_var_labels(dat, new_var_labs)
#' tveDataLoader::get_varLabels(dat)
#'
#' @returns Version of dat with the updated variable labels applied
#' @export
update_var_labels <- function(dat, new_var_labels) {
  assertthat::assert_that(
    is.data.frame(dat),
    msg = "data to relable must be a data frame"
  )
  assertthat::assert_that(
    and(is.data.frame(new_var_labels), ncol(new_var_labels) == 2),
    msg = "new_var_labels should be a data frame with 2 columns"
  )
  assertthat::assert_that(
    all(as.character(sapply(new_var_labels, class)) == rep("character", 2)),
    msg = "Columns of new_var_labels should be character"
  )

  new_var_labels_ls <- split(new_var_labels, new_var_labels[1]) |>
    lapply(tibble::deframe) |>
    lapply(unname)

  dat |>
    labelled::set_variable_labels(.labels = new_var_labels_ls)
}
